import fs from "fs"
import path from "path"
import { registry } from "@/registry/registry"
import { rimraf } from "rimraf"

console.log("📝 Writing registry index...")

const registryPath = path.join(process.cwd(), "/__registry__")

// ----------------------------------------------------------------------------
// Build __registry__/index.tsx.
// ----------------------------------------------------------------------------
let index = `// @ts-nocheck
// This file is autogenerated by scripts/registry-builder.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`
console.log(process.cwd())

// Build style index.
for (const item of registry) {
  const resolveFiles = item.files.map((file) => `/registry/${file}`)
  const type = item.type.split(":")[1]

  index += `
  "${item.name}": {
    name: "${item.name}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    component: React.lazy(() => import("@/registry/${type}/${item.name}")),
    files: [${resolveFiles.map((file) => `"${file}"`)}],
  },`
}

index += `
}`

if (!fs.existsSync(registryPath)) {
  fs.mkdirSync(registryPath)
}
// Write style index.
rimraf.sync(path.join(process.cwd(), "/__registry__/index.tsx"))
fs.writeFileSync(path.join(process.cwd(), "/__registry__/index.tsx"), index)

console.log("✅ Done!")
