import type { Metadata } from "next"

import "./globals.css"

import { fontMono, fontSans } from "@/lib/fonts"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(`${fontSans.variable} ${fontMono.variable} font-sans`)}
      >
        {children}
      </body>
    </html>
  )
}
