import type { Metadata } from "next"
import { Roboto_Mono as FontMono, Inter as FontSans } from "next/font/google"

import "@/styles/globals.css"

import { CommandMenuProvider } from "@/context/command-menu-provider"

import { cn } from "@/lib/utils"
import { CommandMenu } from "@/components/command-menu"
import Footer from "@/components/layout/footer"
import Header from "@/components/layout/header"
import { ThemeProvider } from "@/components/theme-provider"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const fontCode = FontMono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-pt-[48px]">
      <body
        className={cn(
          "min-h-dvh bg-background font-sans antialiased",
          fontSans.variable,
          fontCode.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <CommandMenuProvider>
            <div className="relative flex min-h-dvh flex-col bg-background">
              <Header />
              <main className="flex flex-1 items-center justify-center">
                {children}
              </main>
              <Footer />
              <CommandMenu />
            </div>
          </CommandMenuProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
