// @ts-nocheck
// This file is autogenerated by scripts/registry-builder.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "glitch-demo": {
    name: "glitch-demo",
    type: "components:example",
    registryDependencies: undefined,
    component: React.lazy(() => import("@/registry/example/glitch-demo")),
    files: ["/registry/example/glitch-demo.tsx"],
  },
}